name: macOS build and codesign

on:
  workflow_dispatch: # Enables manual trigger from GitHub UI

jobs:
  code-signing:
    runs-on: macos-latest
    environment: macos-codesign
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.70
      - name: build
        run: |
          ./build_tools/make_pkg.sh
      - name: Execute Code Signing Script
        run: ./mac_codesign.sh
        env:
          MAC_CODESIGN_P12_BASE64: ${{ secrets.MAC_CODESIGN_P12_BASE64 }}
          MAC_CODESIGN_PASSWORD: ${{ secrets.MAC_CODESIGN_PASSWORD }}
          # macOS runners keep having issues loading Cargo.toml dependencies from git (GitHub) instead
          # of crates.io, so give this a try. It's also sometimes significantly faster on all platforms.
          CARGO_NET_GIT_FETCH_WITH_CLI: true
          FISH_ARTEFACT_PATH: /tmp/fish-built
